### ISSUE TITLE
Layers not updating after changing source

### ISSUE THREAD

**Issue by Ben-Guthrie** [NathanielJenkins/SkiMap#32]
Steps to replicate:

- Navigate directly to https://skimap.netlify.app/real_map
- Change maps
- All the features from the real map are still visible in the top left (at the location of these features on the world map)

The same is probably happening with changing maps the other way as well, it's just outside the map bounds so isn't visible. Only happens once per load - after the map has been cached this no longer happens

**Comment by chs-nathan** [comment]
Could not replicate
